### ISSUE TITLE
Library generates invalid QR code

### ISSUE THREAD

**Issue by AndreasGassmann** [kazuhikoarase/qrcode-generator#109]
We built a library ([beacon-sdk](https://github.com/airgap-it/beacon-sdk/blob/master/src/utils/qr.ts#L28)) that is using this library to generate QR codes. There are many apps using our library and it works without any issues.

However, I recently tried adding our library to a specific [react project](https://github.com/AndreasGassmann/apps) and for some reason, the QR code that is generated on that site is invalid. It seems to have a weird "pattern" as shown in the example below.

Because it works without any problems in 99% of the cases, I'm pretty sure this is somehow related to the project I'm using it in (which is using a reactjs library that itself also relies on `qrcode-generator`. But nonetheless, the error seems to happen within this library. 

I have no idea how I can go about fixing this issue because everything looks good code wise. Do you have any idea what could be going on? Thanks so much for any help.

This is the code that I'm using to generate the invalid QR code:

## Code

```javascript
const typeNumber = 0;
const errorCorrectionLevel = 'L';
const qr = qrcode(typeNumber, errorCorrectionLevel);

qr.addData('this is a test. this is a test. this is a test. this is a test.');
qr.make();

console.log(qr.createASCII());

return qr.createSvgTag();
```

## Examples

![qr-pattern](https://user-images.githubusercontent.com/680814/156452648-c8ab8621-5bd1-421b-8957-ad53bb008792.png)

Ascii (in the browser log):
```
█████████████████████████████████████
██ ▄▄▄▄▄ █ ▀▀▄ ▄▄▄▄▄▄▄▄▄▄▄▄█ ▄▄▄▄▄ ██
██ █   █ ███ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄█ █   █ ██
██ █▄▄▄█ █ ▄▄ █▄▄▄▄▄▄▄▄▄▄▄▄█ █▄▄▄█ ██
██▄▄▄▄▄▄▄█ █ ▀ █▄█▄█▄█▄█▄█▄█▄▄▄▄▄▄▄██
██▄▄▄█▀ ▄▀   ██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██▄▄██
██▄█▀▀▄ ▄▄ ▀█▄█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
██ ▄███▄▄██ █▄ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
███▄▀ ██▄ ▄▄▄▀ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
██  █▀▄▄▄ ▀▀ ██ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
██▀▀ █▀█▄▀▄██▄█▀█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
██▄██ █▄▄█   ▄ ▄█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
██▄▄█ █▄▄▄█▀▄▀ ▄ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
██▄▄█▄▄█▄█ █▄██  ▄▄▄▄▄▄▄▄▄ ▄▄▄ ▄▄▄▄██
██ ▄▄▄▄▄ █▀▄█▄█▀█▄▄▄▄▄▄▄▄▄ █▄█ ▄▄  ██
██ █   █ ██▄█▄ ▄█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀▀██
██ █▄▄▄█ █ ▀ ▀ ▄ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
██▄▄▄▄▄▄▄█▄█▄██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█▄██
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
```

This happens when I change the error correction code to "H":

![qr-h](https://user-images.githubusercontent.com/680814/156459008-d72720eb-46e2-496e-9767-3b9d83f985e9.png)

This happens when I change the data to:

```
qr.addData('this is a test. this is a test. this is a test. this is a test. this is a test. this is a test. this is a test. this is a test. this is a test. this is a test. this is a test. this is a test.');
```
L: 
![qr-2-l](https://user-images.githubusercontent.com/680814/156459042-78b36a37-6b50-4210-8dd2-8fe957dd9b43.png)

H:

![qr-2-h](https://user-images.githubusercontent.com/680814/156459029-be4cc7d8-44ce-4059-9e3f-d858317bae66.png)

```
qr.addData('test');
```

L:
![qr-test](https://user-images.githubusercontent.com/680814/156459069-d402647e-f8d6-47e6-b4e6-f285b78a341b.png)

**Comment by kazuhikoarase** [comment]
Hi,
Thanks for your report.
But I could not reproduce it..

![image](https://user-images.githubusercontent.com/1137546/156464106-beabe7fa-d8bf-42df-944c-872ffed80111.png)
![image](https://user-images.githubusercontent.com/1137546/156464319-bf24bfb9-8b50-4112-8603-9c27eed11e01.png)

**Comment by AndreasGassmann** [comment]
Yes, under normal circumstances it works without any issues. It is *only* when used in [this specific project](https://github.com/AndreasGassmann/apps) that the resulting QR codes are wrong.

I was hoping you could give me some pointers about how I could go about debugging this. Because the code from this library that I call is very minimal, so somehow the internal state / logic of this module is affected by something in that project that breaks it. The pattern that is generated, could you explain how this could happen?

**Comment by AndreasGassmann** [comment]
I found the issue. One of the libraries that was used in that project overwrote the `stringToBytes` method of this library, which broke the functionality when passing in a regular string.

Sorry for wasting your time and thanks for creating this great library.
