### ISSUE TITLE
add quiet zone on javascript version

### ISSUE THREAD

**Issue by sombriks** [kazuhikoarase/qrcode-generator#17]
hello,

is there a way to add a [quiet zone](http://www.jeffkorhan.com/2011/08/3-best-practices-for-generating-reliable-qr-codes.html) on the generated qr-code?

i'm using the javascript version and when i donwload the image some scanners can't read due some black backgrounds. on my page it works perfectly, but once i download it the issue emerges.

**Comment by kazuhikoarase** [comment]
Hi,
What api do you use? By default, createImgTag function generates 8px of margin (quiet zone).

```javascript
var create_qrcode = function(text, typeNumber, errorCorrectLevel, table) {
  var qr = qrcode(typeNumber || 4, errorCorrectLevel || 'M');
  qr.addData(text);
  qr.make();
  return qr.createImgTag();
};

var update_qrcode = function() {
  var form = document.forms['qrForm'];
  var text = form.elements['msg'].value.replace(/^[\s\u3000]+|[\s\u3000]+$/g, '');
  var t = form.elements['t'].value;
  var e = form.elements['e'].value;
  document.getElementById('qr').innerHTML = create_qrcode(text, t, e);
};
```

**Comment by sombriks** [comment]
Hello,

bower.json says 0.0.2

however i'm using [angular-qrcode](https://github.com/monospaced/angular-qrcode), maybe the lack of a quiet zone issue comes from there.

My apologizes.
