### ISSUE TITLE
White border around QR code

### ISSUE THREAD

**Issue by obsidianart** [kazuhikoarase/qrcode-generator#18]
I'm trying to remove the white border/padding around the QR code. Is there any option to generate a QR code without a white frame around?
Thanks

**Comment by kazuhikoarase** [comment]
Hi,
What api do you use?
In case createImgTag function of javascript, you could apply zero on second argument to no margin. 
see also https://github.com/kazuhikoarase/qrcode-generator/issues/17
```javascript
var create_qrcode = function(text, typeNumber, errorCorrectLevel, table) {
  var qr = qrcode(typeNumber || 4, errorCorrectLevel || 'M');
  qr.addData(text);
  qr.make();
  return qr.createImgTag(2, 0);
};
```

**Comment by obsidianart** [comment]
Thank you, I was using createImgBase64 but I didn't notice there was an option
