### ISSUE TITLE
import failed in TypeScript, and require is ok.

### ISSUE THREAD

**Issue by Fukai-AC** [kazuhikoarase/qrcode-generator#25]
Hi, In TypeScript file, i use import('qrcode-generator') but there is an error of 'can't find the moudle' while i change 'import' into 'require' and it works. But since we start to use TypeScript2.0, we will not use require.
I think it may because there doesn't refer to the .d.ts file in the package.json.
Please resolve it.
Thank you!

**Comment by kazuhikoarase** [comment]
Hi,
I have just published.
Is this works fine?
qrcode-generator@1.0.7

**Comment by Fukai-AC** [comment]
Oh, It works. It has been a great help. Thank you!
