### ISSUE TITLE
Is there a way to manually set the mode to alphanumeric?

### ISSUE THREAD

**Issue by enjoiful** [kazuhikoarase/qrcode-generator#28]
Can I manually force the generator to encode data using Alphanumeric mode, instead of Binary mode?

I'm finding out that for a Version=2, DataCorrection=H, I can only fit 14 characters into the QR code.  This is inline with the character limits for a "Binary" QR Code. However, I want to encode with Alphanumeric.  

It looks like the generator only accepts Version and DataCorrection inputs, and does not allow you to specify mode (Binary, Alphanumeric, Kanji, Numeric).   Am I missing something?

**Comment by kazuhikoarase** [comment]
I added a second parameter 'mode' to function addData.
You can set one of 'Numeric', 'Alphanumeric', 'Byte', 'Kanji' explictly.

https://kazuhikoarase.github.io/qrcode-generator/

Thanks.

**Comment by enjoiful** [comment]
Works great, thanks!
