### ISSUE TITLE
Typings ?

### ISSUE THREAD

**Issue by aljibbs** [kazuhikoarase/qrcode-generator#30]
Will you be adding typings definition for this library ?
Wish I could use it in an angular2 and Ionic 2 project

**Comment by kazuhikoarase** [comment]
Hi,
Isn't this what you mean?
https://github.com/kazuhikoarase/qrcode-generator/blob/master/js/qrcode.d.ts

**Comment by aljibbs** [comment]
Great...I guess I didn't take my time to look through the files. Thanks for the quick response. Great library
