### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bowlofeggs** [kazuhikoarase/qrcode-generator#32]
It's been a while since this project has made a release. I'm working on packaging it for Fedora, and it would be nice to have a recent release. Thanks!

**Comment by kazuhikoarase** [comment]
Hi,

I do it just now.

Thank you.

**Comment by larrylballes** [comment]
I need a letter NE of code to enter funds on Google wallet

**Comment by larrylballes** [comment]
A line of code

**Comment by larrylballes** [comment]
Please
