### ISSUE TITLE
including Chinese in the qrcode by the javascript

### ISSUE THREAD

**Issue by guguji5** [kazuhikoarase/qrcode-generator#33]
when I include the chinese in the qrcode,it's turn to be a massy code

**Comment by kazuhikoarase** [comment]
Hi,
Multibyte encoding of my sample site was fixed to SJIS and it was effective for japanese only.
Now, I change default encoding to UTF-8 and it can be change dynamically.
Thank you.

https://kazuhikoarase.github.io/qrcode-generator/

**Comment by guguji5** [comment]
tkanks a lot,it save me a lot of time because of your help.it suprise me that you are a japanese developer.what's the technical atmosphere of the Frontend in Japan 。

**Comment by kazuhikoarase** [comment]
Mostly projects are migration from the legacy system and  taking a lot of cost for character conversion, encoding and Wareki (i.e. Heisei, Showa, ...) conversion. There are not technical and nothing interesting. 
So I must try a modern programming on github :)

**Comment by guguji5** [comment]
hello,it's me again.I plan use your qrcode plugin in Vanke  marketing systems(Top 500 in world).the qr may be used very frequently.so **is there any way to improve the success ratio of scanning**.my data including in the qrcode is very large.and the qr is very  thickly dotted.
the data i want to include:
`{"signature":"b59c67bf196a4758191e42f76670ceba+201703161800",
    "client":"vanke",
    "content":{
        "receiptNo":"800000000019",
        "houseName":"万科公园里-一期3栋302",
        "paymentHouseNo":"string",
        "contractWithTaxPrice":"2000000",
        "receiptMode ":"SD3001003",
        "customerName":"张三",
        "depositBankAccount":"2030382903020",
        "thisAmount":"3000",
        "receivedMoney":"2000"
}
`
it's a pleasure to hear from you

**Comment by kazuhikoarase** [comment]
What paraeters did you use?
I try your data at my demo site and get a quick response.

TypeNumber: 15
ErrorCorrectionLevel: M
Mode: Byte
MB: UTF-8

http://kazuhikoarase.github.io/qrcode-generator/

**Comment by guguji5** [comment]
hello,your plugin is well done in my project.now the customer want to improve the appearance of qrcode. is it possible to include a picture in the center of the qrcode?

**Comment by kazuhikoarase** [comment]
Although you must choose a proper error correction level and test it carefully, it possible.

https://en.wikipedia.org/wiki/QR_code#/media/File:2_150_150DPI_ty_oerny_08_2011.jpg

**Comment by Ekko7778** [comment]
查看中文编码问题的讨论
