### ISSUE TITLE
wrong data capacity values on test page

### ISSUE THREAD

**Issue by edcoumont** [kazuhikoarase/qrcode-generator#42]
Data capacity in the table on test page https://kazuhikoarase.github.io/qrcode-generator/
do not match the max values indicated here http://www.qrcode.com/en/about/version.html

For TypeNumber 1, your table has the following values :
- Numeric M : 25
- AlphaNum L : 34

While official values are :
- Numeric M : 34
- AlphaNum L : 25

It seems like the whole table has been reversed.

**Comment by kazuhikoarase** [comment]
Hi,
I had fixed.
Thank you.
