### ISSUE TITLE
Alphanumeric mode does not work

### ISSUE THREAD

**Issue by shinichi77** [kazuhikoarase/qrcode-generator#43]
Hi. When I try the alphanumeric mode, with any text (e.g. "here comes qr", it throws an error "Uncaught illegal char :h" in the console and no qr code is displayed.  Is it a known issue and is going to be fixed?

**Comment by kazuhikoarase** [comment]
Hi,
The alphanumeric mode supports upper case only.
https://en.wikipedia.org/wiki/QR_code
