### ISSUE TITLE
Importing the Kanji support file in Node.js

### ISSUE THREAD

**Issue by no23reason** [kazuhikoarase/qrcode-generator#47]
Hello, I am confused as on how to import the Kanji `qrcode_SJIS` file in Node.js. When I tried:
```
const qrcode = require("qrcode-generator")
require("qrcode-generator/qrcode_SJIS")
const qr = qrcode(0, "L");
qr.addData(`敦煌天空的沙礫帶著我們的記憶`, `Kanji`);
qr.make();
console.log(qr.createSvgTag());
```
it died on an reference error in the `qrcode_SJIS` saying that `qrcode` is not defined 😕
Can you please provide an example on how to do this?

**Comment by kazuhikoarase** [comment]
There are two problems.
1. qrcode_SJIS.js is not ready for nodejs
2. Chinese characters are similar with Japanese but not SJIS and so you should use Bytes/UTF-8 instead of Kanji/SJIS.

Try this.
https://runkit.com/embed/xl2ig6ti9z7e

**Comment by no23reason** [comment]
Thank you for your reply, this works for me. Closing.
