### ISSUE TITLE
createASCII without margin error

### ISSUE THREAD

**Issue by jlami** [kazuhikoarase/qrcode-generator#66]
When I call createASCII with a margin of 0 and when the size of the qr code is odd, the last line is cut of and replaced with a half border.

I think the condition to substring and concat the half border should be `if (*size % 2) && r)` at https://github.com/kazuhikoarase/qrcode-generator/blob/a4ce043c3d8edcb469f07d2db9d4da3527d23f41/js/qrcode.js#L619

https://codepen.io/anon/pen/KJdwXg

**Comment by ahwayakchih** [comment]
@jlami thanks for report.

I could reproduce it only for cell size set to 1. With cell sizes bigger than 2, generated output was OK here.

Please check fix from #68 and confirm it works :).

**Comment by jlami** [comment]
Yes this works!

**Comment by ahwayakchih** [comment]
Great! Thanks :).
