### ISSUE TITLE
Feature request: Add tag when a new js version is available

### ISSUE THREAD

**Issue by babelouest** [kazuhikoarase/qrcode-generator#75]
Hello,

In order to be able to follow-up new version of qrcode.js, is it possible to add tags in the github repository when a new javascript version is released?

**Comment by kazuhikoarase** [comment]
Hi,

I added tag 'js1.4.4' to current.
Next time I'll publish to npmjs, add as same.

Thank you.

**Comment by babelouest** [comment]
Thanks a lot!
