### ISSUE TITLE
how to change qrcode color

### ISSUE THREAD

**Issue by huang-x-h** [kazuhikoarase/qrcode-generator#82]
Can we change the qrcode from black to green?

**Comment by kazuhikoarase** [comment]
Hi, What language of qrcode geenrator do you use?

**Comment by huang-x-h** [comment]
use dataURL `data:image/gif;base64,`

**Comment by huang-x-h** [comment]
@kazuhikoarase hi, any plan to support colorful qrcode ?

**Comment by kazuhikoarase** [comment]
@huang-x-h I have no plan. But you can generate it manually.

https://jsfiddle.net/mfxg1noj/

**Comment by huang-x-h** [comment]
Great, thanks a lot ! 👍

**Comment by Uluer** [comment]
> 使用dataURL `data:image/gif;base64,`

https://github.com/kazuhikoarase/qrcode-generator/blob/master/js/qrcode.js
第2045行
` // black
      out.writeByte(0x00);
      out.writeByte(0x00);
      out.writeByte(0x00);`
修改值，这3个值对应rgb的3个值

**Comment by ygoe** [comment]
> 修改值，这3个值对应rgb的3个值

Yes, that's what I did.
